author = 'Avinash Rijal'
description = "Hi! I am Avinash Rijal. A Full stack web developer and DevOps Engineer from Nepal."
logo = '/avinash-icon.png'

[social]
  twitter = 'http://twitter.com/avinashrijal'
  github = 'https://github.com/zaffron'
  linkedin = 'https://linkedin.com/in/dev-avinash-rijal/'
  instagram = 'https://instagram.com/zaffing'
  youtube = 'https://youtube.com/channel/UC5bcQ0iZFpGWq7FI4mH3Jtw/about'
  facebook = 'https://facebook.com/avlas.rijal'

[contact]
  email = 'avinashrijal@gmail.com'
  phone = '+66916667535'

[address]
  city = 'Bangkok'
  region = 'Phra Khanong'
  country = 'Thailand'
  zipCode = '10260'

[seo]
  defaultOGImage = '/og-default.png'
  twitterHandle = '@avinashrijal'
